CREATE TABLE IF NOT EXISTS contact_info (
    id TINYINT UNSIGNED PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(64) NOT NULL,
    email VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CHECK (id = 1),
);